type Book {
  id: ID!
  name: String!
  title: String!
  userId: Int!
  author: Author!
}

type Author {
  id: ID!
  email: String!
  profile: Profile!

}

input CreateBookInput {
  name: String!
  title: String!
  userId: Int!
}

input UpdateBookInput {
  id: Int!
  name: String!
  title: String!
  userId: Int!
}




